[platformio]
default_envs = audio-proto

[env:audio-proto]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -DAUDIO_DEBUG_PIN=-1
    -DAUDIO_I2S_BCLK_PIN=16
    -DAUDIO_I2S_DOUT_PIN=18
    -DAUDIO_SAMPLE_RATE_TARGET=44100
monitor_speed = 115200
upload_protocol = picotool
