#!/usr/bin/env bun
// Compile a BASIC source to a C header with embedded bytecode.
// Usage: bun compile_game.ts [source.bas] [output.h]
//
// If no source is given, compiles the built-in starfield demo.
// If no output is given, writes to game_bytecode.h.

import { compile, isCompileError } from "../../web/src/basic/compiler.ts";
import { assemble, isError } from "../../web/src/assembler/assembler.ts";

// --- Extract the starfield source from demos.ts ---
const STARFIELD_SOURCE = `' ── Starfield ────────────────────────────────────────────────────
' 50/50 dithered background, scrolling stars, bouncing balls.
' All movement handled by the sprite engine — zero per-frame CPU.

' ── Graphics DATA ────────────────────────────────────────────────
' Dither tile: 128x2 checkerboard (32 bytes)
DATA dither, $55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$55,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA

' 1x1 star pixel
DATA star_gfx, $80

' Filled circle 8x8
DATA ball8, $3C,$7E,$FF,$FF,$FF,$FF,$7E,$3C

' Filled circle 12x12 (row-aligned: 2 bytes/row, 24 bytes total)
DATA ball12, $0F,$00,$3F,$C0,$7F,$E0,$7F,$E0,$FF,$F0,$FF,$F0,$FF,$F0,$FF,$F0,$7F,$E0,$7F,$E0,$3F,$C0,$0F,$00

' ── Sprite layout: 0-4 = balls, 5-31 = stars (27 stars) ─────────

' ── Initialize balls (slots 0-4) ─────────────────────────────────
' Velocity unit: 64 = 1 px/frame. Firmware uses 1-3 dx, 1-2 dy.
FOR i = 0 TO 4
  bw = 8
  gfx = ball8
  IF RAND() AND 1 THEN
    bw = 12
    gfx = ball12
  END IF

  bx = bw + RAND() MOD (128 - 2 * bw)
  by = bw + RAND() MOD (64 - 2 * bw)

  vx = 64 + RAND() MOD 192
  IF RAND() AND 1 THEN vx = 0 - vx
  vy = 64 + RAND() MOD 128
  IF RAND() AND 1 THEN vy = 0 - vy

  SPRITE i, gfx, bw, bw, bx, by, 0, vx, vy, EDGE_BOUNCE
NEXT

' ── Initialize stars (slots 5-31) ────────────────────────────────
' Stars scroll left at varying speeds and wrap around.
FOR i = 5 TO 31
  sx = RAND() MOD 128
  sy = RAND() MOD 64
  speed = 0 - (64 + RAND() MOD 192)
  SPRITE i, star_gfx, 1, 1, sx, sy, 0, speed, 0, EDGE_WRAP
NEXT

' Main loop — just draw the dither background each frame.
DO
  FOR y = 0 TO 62 STEP 2
    BLIT dither, 0, y, 128, 2
  NEXT
  YIELD
LOOP
`;

const args = process.argv.slice(2);
const sourceFile = args[0] && args[0] !== "" ? args[0] : null;
const outputFile = args[1] ?? "game_bytecode.h";

let source: string;
let sourceName: string;
if (sourceFile) {
  source = await Bun.file(sourceFile).text();
  sourceName = sourceFile;
} else {
  source = STARFIELD_SOURCE;
  sourceName = "starfield demo (built-in)";
}

// Step 1: BASIC → assembly
const asmResult = compile(source);
if (isCompileError(asmResult)) {
  console.error(`Compile error (${asmResult.phase}) at line ${asmResult.line}:${asmResult.col}: ${asmResult.message}`);
  process.exit(1);
}

console.error("Assembly output:");
console.error(asmResult);

// Step 2: assembly → bytecode
const binResult = assemble(asmResult);
if (isError(binResult)) {
  console.error(`Assembler error at line ${binResult.line}: ${binResult.message}`);
  process.exit(1);
}

const bytecode = binResult.bytecode;
console.error(`\nBytecode: ${bytecode.length} bytes`);

// Step 3: Generate C header
const lines: string[] = [];
lines.push("#pragma once");
lines.push("// Auto-generated by compile_game.ts — do not edit");
lines.push("// Source: " + sourceName);
lines.push(`// Size: ${bytecode.length} bytes`);
lines.push("");
lines.push("#include <cstdint>");
lines.push("");
lines.push("static const uint8_t GAME_PROGRAM[] = {");

// Format as 16 bytes per line
for (let i = 0; i < bytecode.length; i += 16) {
  const chunk = bytecode.slice(i, Math.min(i + 16, bytecode.length));
  const hex = Array.from(chunk).map(b => `0x${b.toString(16).padStart(2, "0")}`).join(", ");
  const isLast = i + 16 >= bytecode.length;
  lines.push(`    ${hex}${isLast ? "" : ","}`);
}

lines.push("};");
lines.push("");
lines.push(`static const uint16_t GAME_PROGRAM_SIZE = ${bytecode.length};`);
lines.push("");

const header = lines.join("\n");
await Bun.write(outputFile, header);
console.error(`Wrote ${outputFile} (${bytecode.length} bytes)`);
