[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0m
build_flags =
    -DUSE_TINYUSB
    -std=gnu++17
    -Wall -Wextra
board_build.arduino.earlephilhower.usb_vid = 0xCafe
board_build.arduino.earlephilhower.usb_pid = 0x4003
board_build.arduino.earlephilhower.usb_manufacturer = Pico Gamer
board_build.arduino.earlephilhower.usb_product = PICO GAMER
upload_protocol = picotool
lib_deps =
    mathertel/RotaryEncoder@^1.5.3
